/* tslint:disable */
/* eslint-disable */
/**
 * api node tometome
 * API documentation.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  JwtAppleMusicNameGet200Response,
} from '../models/index';
import {
    JwtAppleMusicNameGet200ResponseFromJSON,
    JwtAppleMusicNameGet200ResponseToJSON,
} from '../models/index';

export interface JwtAppleMusicNameGetRequest {
    name: string;
}

/**
 * 
 */
export class DefaultApi extends runtime.BaseAPI {

    /**
     * Creates request options for jwtAppleMusicNameGet without sending the request
     */
    async jwtAppleMusicNameGetRequestOpts(requestParameters: JwtAppleMusicNameGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['name'] == null) {
            throw new runtime.RequiredError(
                'name',
                'Required parameter "name" was null or undefined when calling jwtAppleMusicNameGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/jwt/apple/music/{name}`;
        urlPath = urlPath.replace(`{${"name"}}`, encodeURIComponent(String(requestParameters['name'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async jwtAppleMusicNameGetRaw(requestParameters: JwtAppleMusicNameGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<JwtAppleMusicNameGet200Response>> {
        const requestOptions = await this.jwtAppleMusicNameGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => JwtAppleMusicNameGet200ResponseFromJSON(jsonValue));
    }

    /**
     */
    async jwtAppleMusicNameGet(requestParameters: JwtAppleMusicNameGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<JwtAppleMusicNameGet200Response> {
        const response = await this.jwtAppleMusicNameGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
