/* tslint:disable */
/* eslint-disable */
/**
 * api node tometome
 * API documentation.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  V1YoutubeReleasesGet200Response,
} from '../models/index';
import {
    V1YoutubeReleasesGet200ResponseFromJSON,
    V1YoutubeReleasesGet200ResponseToJSON,
} from '../models/index';

export interface V1YoutubeReleasesGetRequest {
    channelid: string;
}

/**
 * 
 */
export class YouTubeApi extends runtime.BaseAPI {

    /**
     * リリースされたアルバムのリストを返します。
     */
    async v1YoutubeReleasesGetRaw(requestParameters: V1YoutubeReleasesGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<V1YoutubeReleasesGet200Response>> {
        if (requestParameters['channelid'] == null) {
            throw new runtime.RequiredError(
                'channelid',
                'Required parameter "channelid" was null or undefined when calling v1YoutubeReleasesGet().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['channelid'] != null) {
            queryParameters['channelid'] = requestParameters['channelid'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/v1/youtube/releases`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => V1YoutubeReleasesGet200ResponseFromJSON(jsonValue));
    }

    /**
     * リリースされたアルバムのリストを返します。
     */
    async v1YoutubeReleasesGet(requestParameters: V1YoutubeReleasesGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<V1YoutubeReleasesGet200Response> {
        const response = await this.v1YoutubeReleasesGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
