/* tslint:disable */
/* eslint-disable */
/**
 * api node tometome
 * API documentation.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface JwtAppleMusicNameGet200Response
 */
export interface JwtAppleMusicNameGet200Response {
    /**
     * 
     * @type {string}
     * @memberof JwtAppleMusicNameGet200Response
     */
    token?: string;
}

/**
 * Check if a given object implements the JwtAppleMusicNameGet200Response interface.
 */
export function instanceOfJwtAppleMusicNameGet200Response(value: object): value is JwtAppleMusicNameGet200Response {
    return true;
}

export function JwtAppleMusicNameGet200ResponseFromJSON(json: any): JwtAppleMusicNameGet200Response {
    return JwtAppleMusicNameGet200ResponseFromJSONTyped(json, false);
}

export function JwtAppleMusicNameGet200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): JwtAppleMusicNameGet200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'token': json['token'] == null ? undefined : json['token'],
    };
}

export function JwtAppleMusicNameGet200ResponseToJSON(json: any): JwtAppleMusicNameGet200Response {
    return JwtAppleMusicNameGet200ResponseToJSONTyped(json, false);
}

export function JwtAppleMusicNameGet200ResponseToJSONTyped(value?: JwtAppleMusicNameGet200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'token': value['token'],
    };
}

