/* tslint:disable */
/* eslint-disable */
/**
 * api node tometome
 * API documentation.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { V1XPostsGet200ResponsePostsInnerReplyId } from './V1XPostsGet200ResponsePostsInnerReplyId';
import {
    V1XPostsGet200ResponsePostsInnerReplyIdFromJSON,
    V1XPostsGet200ResponsePostsInnerReplyIdFromJSONTyped,
    V1XPostsGet200ResponsePostsInnerReplyIdToJSON,
    V1XPostsGet200ResponsePostsInnerReplyIdToJSONTyped,
} from './V1XPostsGet200ResponsePostsInnerReplyId';
import type { V1XPostsGet200ResponsePostsInnerMediasInner } from './V1XPostsGet200ResponsePostsInnerMediasInner';
import {
    V1XPostsGet200ResponsePostsInnerMediasInnerFromJSON,
    V1XPostsGet200ResponsePostsInnerMediasInnerFromJSONTyped,
    V1XPostsGet200ResponsePostsInnerMediasInnerToJSON,
    V1XPostsGet200ResponsePostsInnerMediasInnerToJSONTyped,
} from './V1XPostsGet200ResponsePostsInnerMediasInner';

/**
 * 
 * @export
 * @interface V1XPostsGet200ResponsePostsInner
 */
export interface V1XPostsGet200ResponsePostsInner {
    /**
     * 
     * @type {string}
     * @memberof V1XPostsGet200ResponsePostsInner
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof V1XPostsGet200ResponsePostsInner
     */
    text?: string;
    /**
     * 
     * @type {Date}
     * @memberof V1XPostsGet200ResponsePostsInner
     */
    publishedAt?: Date;
    /**
     * 
     * @type {string}
     * @memberof V1XPostsGet200ResponsePostsInner
     */
    userId?: string;
    /**
     * 
     * @type {V1XPostsGet200ResponsePostsInnerReplyId}
     * @memberof V1XPostsGet200ResponsePostsInner
     */
    replyId?: V1XPostsGet200ResponsePostsInnerReplyId;
    /**
     * 
     * @type {V1XPostsGet200ResponsePostsInnerReplyId}
     * @memberof V1XPostsGet200ResponsePostsInner
     */
    repostId?: V1XPostsGet200ResponsePostsInnerReplyId;
    /**
     * 
     * @type {V1XPostsGet200ResponsePostsInnerReplyId}
     * @memberof V1XPostsGet200ResponsePostsInner
     */
    quoteRepostId?: V1XPostsGet200ResponsePostsInnerReplyId;
    /**
     * 
     * @type {Array<string>}
     * @memberof V1XPostsGet200ResponsePostsInner
     */
    urls?: Array<string>;
    /**
     * 
     * @type {Array<V1XPostsGet200ResponsePostsInnerMediasInner>}
     * @memberof V1XPostsGet200ResponsePostsInner
     */
    medias?: Array<V1XPostsGet200ResponsePostsInnerMediasInner>;
}

/**
 * Check if a given object implements the V1XPostsGet200ResponsePostsInner interface.
 */
export function instanceOfV1XPostsGet200ResponsePostsInner(value: object): value is V1XPostsGet200ResponsePostsInner {
    return true;
}

export function V1XPostsGet200ResponsePostsInnerFromJSON(json: any): V1XPostsGet200ResponsePostsInner {
    return V1XPostsGet200ResponsePostsInnerFromJSONTyped(json, false);
}

export function V1XPostsGet200ResponsePostsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1XPostsGet200ResponsePostsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'text': json['text'] == null ? undefined : json['text'],
        'publishedAt': json['published_at'] == null ? undefined : (new Date(json['published_at'])),
        'userId': json['user_id'] == null ? undefined : json['user_id'],
        'replyId': json['reply_id'] == null ? undefined : V1XPostsGet200ResponsePostsInnerReplyIdFromJSON(json['reply_id']),
        'repostId': json['repost_id'] == null ? undefined : V1XPostsGet200ResponsePostsInnerReplyIdFromJSON(json['repost_id']),
        'quoteRepostId': json['quote_repost_id'] == null ? undefined : V1XPostsGet200ResponsePostsInnerReplyIdFromJSON(json['quote_repost_id']),
        'urls': json['urls'] == null ? undefined : json['urls'],
        'medias': json['medias'] == null ? undefined : ((json['medias'] as Array<any>).map(V1XPostsGet200ResponsePostsInnerMediasInnerFromJSON)),
    };
}

export function V1XPostsGet200ResponsePostsInnerToJSON(json: any): V1XPostsGet200ResponsePostsInner {
    return V1XPostsGet200ResponsePostsInnerToJSONTyped(json, false);
}

export function V1XPostsGet200ResponsePostsInnerToJSONTyped(value?: V1XPostsGet200ResponsePostsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'text': value['text'],
        'published_at': value['publishedAt'] == null ? undefined : ((value['publishedAt']).toISOString()),
        'user_id': value['userId'],
        'reply_id': V1XPostsGet200ResponsePostsInnerReplyIdToJSON(value['replyId']),
        'repost_id': V1XPostsGet200ResponsePostsInnerReplyIdToJSON(value['repostId']),
        'quote_repost_id': V1XPostsGet200ResponsePostsInnerReplyIdToJSON(value['quoteRepostId']),
        'urls': value['urls'],
        'medias': value['medias'] == null ? undefined : ((value['medias'] as Array<any>).map(V1XPostsGet200ResponsePostsInnerMediasInnerToJSON)),
    };
}

