/* tslint:disable */
/* eslint-disable */
/**
 * api node tometome
 * API documentation.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { V1XPostsGet200ResponsePostsInnerReplyId } from './V1XPostsGet200ResponsePostsInnerReplyId';
import {
    V1XPostsGet200ResponsePostsInnerReplyIdFromJSON,
    V1XPostsGet200ResponsePostsInnerReplyIdFromJSONTyped,
    V1XPostsGet200ResponsePostsInnerReplyIdToJSON,
    V1XPostsGet200ResponsePostsInnerReplyIdToJSONTyped,
} from './V1XPostsGet200ResponsePostsInnerReplyId';
import type { V1XPostsGet200ResponsePostsInnerMediasInnerMediaAspectRatio } from './V1XPostsGet200ResponsePostsInnerMediasInnerMediaAspectRatio';
import {
    V1XPostsGet200ResponsePostsInnerMediasInnerMediaAspectRatioFromJSON,
    V1XPostsGet200ResponsePostsInnerMediasInnerMediaAspectRatioFromJSONTyped,
    V1XPostsGet200ResponsePostsInnerMediasInnerMediaAspectRatioToJSON,
    V1XPostsGet200ResponsePostsInnerMediasInnerMediaAspectRatioToJSONTyped,
} from './V1XPostsGet200ResponsePostsInnerMediasInnerMediaAspectRatio';

/**
 * 
 * @export
 * @interface V1XPostsGet200ResponsePostsInnerMediasInnerMedia
 */
export interface V1XPostsGet200ResponsePostsInnerMediasInnerMedia {
    /**
     * 
     * @type {V1XPostsGet200ResponsePostsInnerReplyId}
     * @memberof V1XPostsGet200ResponsePostsInnerMediasInnerMedia
     */
    url?: V1XPostsGet200ResponsePostsInnerReplyId;
    /**
     * 
     * @type {V1XPostsGet200ResponsePostsInnerMediasInnerMediaAspectRatio}
     * @memberof V1XPostsGet200ResponsePostsInnerMediasInnerMedia
     */
    aspectRatio?: V1XPostsGet200ResponsePostsInnerMediasInnerMediaAspectRatio;
}

/**
 * Check if a given object implements the V1XPostsGet200ResponsePostsInnerMediasInnerMedia interface.
 */
export function instanceOfV1XPostsGet200ResponsePostsInnerMediasInnerMedia(value: object): value is V1XPostsGet200ResponsePostsInnerMediasInnerMedia {
    return true;
}

export function V1XPostsGet200ResponsePostsInnerMediasInnerMediaFromJSON(json: any): V1XPostsGet200ResponsePostsInnerMediasInnerMedia {
    return V1XPostsGet200ResponsePostsInnerMediasInnerMediaFromJSONTyped(json, false);
}

export function V1XPostsGet200ResponsePostsInnerMediasInnerMediaFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1XPostsGet200ResponsePostsInnerMediasInnerMedia {
    if (json == null) {
        return json;
    }
    return {
        
        'url': json['url'] == null ? undefined : V1XPostsGet200ResponsePostsInnerReplyIdFromJSON(json['url']),
        'aspectRatio': json['aspect_ratio'] == null ? undefined : V1XPostsGet200ResponsePostsInnerMediasInnerMediaAspectRatioFromJSON(json['aspect_ratio']),
    };
}

export function V1XPostsGet200ResponsePostsInnerMediasInnerMediaToJSON(json: any): V1XPostsGet200ResponsePostsInnerMediasInnerMedia {
    return V1XPostsGet200ResponsePostsInnerMediasInnerMediaToJSONTyped(json, false);
}

export function V1XPostsGet200ResponsePostsInnerMediasInnerMediaToJSONTyped(value?: V1XPostsGet200ResponsePostsInnerMediasInnerMedia | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'url': V1XPostsGet200ResponsePostsInnerReplyIdToJSON(value['url']),
        'aspect_ratio': V1XPostsGet200ResponsePostsInnerMediasInnerMediaAspectRatioToJSON(value['aspectRatio']),
    };
}

