/* tslint:disable */
/* eslint-disable */
/**
 * api node tometome
 * API documentation.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @type V1XPostsGet200ResponsePostsInnerReplyId
 * 
 * @export
 */
export type V1XPostsGet200ResponsePostsInnerReplyId = string;

export function V1XPostsGet200ResponsePostsInnerReplyIdFromJSON(json: any): V1XPostsGet200ResponsePostsInnerReplyId {
    return V1XPostsGet200ResponsePostsInnerReplyIdFromJSONTyped(json, false);
}

export function V1XPostsGet200ResponsePostsInnerReplyIdFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1XPostsGet200ResponsePostsInnerReplyId {
    if (json == null) {
        return json;
    }
    // if (instanceOfstring(json)) {
    //     return stringFromJSONTyped(json, true);
    // }

    return {} as any;
}

export function V1XPostsGet200ResponsePostsInnerReplyIdToJSON(json: any): any {
    return V1XPostsGet200ResponsePostsInnerReplyIdToJSONTyped(json, false);
}

export function V1XPostsGet200ResponsePostsInnerReplyIdToJSONTyped(value?: V1XPostsGet200ResponsePostsInnerReplyId | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    // if (instanceOfstring(value)) {
    //     return stringToJSON(value as string);
    // }

    return {};
}

