/* tslint:disable */
/* eslint-disable */
/**
 * api node tometome
 * API documentation.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface V1XPostsGet200ResponsePostsInnerMediasInnerImage
 */
export interface V1XPostsGet200ResponsePostsInnerMediasInnerImage {
    /**
     * 
     * @type {string}
     * @memberof V1XPostsGet200ResponsePostsInnerMediasInnerImage
     */
    url?: string;
    /**
     * 
     * @type {number}
     * @memberof V1XPostsGet200ResponsePostsInnerMediasInnerImage
     */
    width?: number;
    /**
     * 
     * @type {number}
     * @memberof V1XPostsGet200ResponsePostsInnerMediasInnerImage
     */
    height?: number;
}

/**
 * Check if a given object implements the V1XPostsGet200ResponsePostsInnerMediasInnerImage interface.
 */
export function instanceOfV1XPostsGet200ResponsePostsInnerMediasInnerImage(value: object): value is V1XPostsGet200ResponsePostsInnerMediasInnerImage {
    return true;
}

export function V1XPostsGet200ResponsePostsInnerMediasInnerImageFromJSON(json: any): V1XPostsGet200ResponsePostsInnerMediasInnerImage {
    return V1XPostsGet200ResponsePostsInnerMediasInnerImageFromJSONTyped(json, false);
}

export function V1XPostsGet200ResponsePostsInnerMediasInnerImageFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1XPostsGet200ResponsePostsInnerMediasInnerImage {
    if (json == null) {
        return json;
    }
    return {
        
        'url': json['url'] == null ? undefined : json['url'],
        'width': json['width'] == null ? undefined : json['width'],
        'height': json['height'] == null ? undefined : json['height'],
    };
}

export function V1XPostsGet200ResponsePostsInnerMediasInnerImageToJSON(json: any): V1XPostsGet200ResponsePostsInnerMediasInnerImage {
    return V1XPostsGet200ResponsePostsInnerMediasInnerImageToJSONTyped(json, false);
}

export function V1XPostsGet200ResponsePostsInnerMediasInnerImageToJSONTyped(value?: V1XPostsGet200ResponsePostsInnerMediasInnerImage | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'url': value['url'],
        'width': value['width'],
        'height': value['height'],
    };
}

