/* tslint:disable */
/* eslint-disable */
/**
 * api node tometome
 * API documentation.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { XPost } from './XPost';
import {
    XPostFromJSON,
    XPostFromJSONTyped,
    XPostToJSON,
    XPostToJSONTyped,
} from './XPost';

/**
 * 
 * @export
 * @interface V1XPostPostIdGet200Response
 */
export interface V1XPostPostIdGet200Response {
    /**
     * 
     * @type {XPost}
     * @memberof V1XPostPostIdGet200Response
     */
    post?: XPost;
}

/**
 * Check if a given object implements the V1XPostPostIdGet200Response interface.
 */
export function instanceOfV1XPostPostIdGet200Response(value: object): value is V1XPostPostIdGet200Response {
    return true;
}

export function V1XPostPostIdGet200ResponseFromJSON(json: any): V1XPostPostIdGet200Response {
    return V1XPostPostIdGet200ResponseFromJSONTyped(json, false);
}

export function V1XPostPostIdGet200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1XPostPostIdGet200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'post': json['post'] == null ? undefined : XPostFromJSON(json['post']),
    };
}

export function V1XPostPostIdGet200ResponseToJSON(json: any): V1XPostPostIdGet200Response {
    return V1XPostPostIdGet200ResponseToJSONTyped(json, false);
}

export function V1XPostPostIdGet200ResponseToJSONTyped(value?: V1XPostPostIdGet200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'post': XPostToJSON(value['post']),
    };
}

