/* tslint:disable */
/* eslint-disable */
/**
 * api node tometome
 * API documentation.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface V1XPostsGet500Response
 */
export interface V1XPostsGet500Response {
    /**
     * 
     * @type {string}
     * @memberof V1XPostsGet500Response
     */
    message?: string;
}

/**
 * Check if a given object implements the V1XPostsGet500Response interface.
 */
export function instanceOfV1XPostsGet500Response(value: object): value is V1XPostsGet500Response {
    return true;
}

export function V1XPostsGet500ResponseFromJSON(json: any): V1XPostsGet500Response {
    return V1XPostsGet500ResponseFromJSONTyped(json, false);
}

export function V1XPostsGet500ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1XPostsGet500Response {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'] == null ? undefined : json['message'],
    };
}

export function V1XPostsGet500ResponseToJSON(json: any): V1XPostsGet500Response {
    return V1XPostsGet500ResponseToJSONTyped(json, false);
}

export function V1XPostsGet500ResponseToJSONTyped(value?: V1XPostsGet500Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': value['message'],
    };
}

