/* tslint:disable */
/* eslint-disable */
/**
 * api node tometome
 * API documentation.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { V1XPostsGet200ResponsePostsInnerMediasInnerMedia } from './V1XPostsGet200ResponsePostsInnerMediasInnerMedia';
import {
    V1XPostsGet200ResponsePostsInnerMediasInnerMediaFromJSON,
    V1XPostsGet200ResponsePostsInnerMediasInnerMediaFromJSONTyped,
    V1XPostsGet200ResponsePostsInnerMediasInnerMediaToJSON,
    V1XPostsGet200ResponsePostsInnerMediasInnerMediaToJSONTyped,
} from './V1XPostsGet200ResponsePostsInnerMediasInnerMedia';
import type { V1XPostsGet200ResponsePostsInnerMediasInnerImage } from './V1XPostsGet200ResponsePostsInnerMediasInnerImage';
import {
    V1XPostsGet200ResponsePostsInnerMediasInnerImageFromJSON,
    V1XPostsGet200ResponsePostsInnerMediasInnerImageFromJSONTyped,
    V1XPostsGet200ResponsePostsInnerMediasInnerImageToJSON,
    V1XPostsGet200ResponsePostsInnerMediasInnerImageToJSONTyped,
} from './V1XPostsGet200ResponsePostsInnerMediasInnerImage';
import type { V1XPostsGet200ResponsePostsInnerReplyId } from './V1XPostsGet200ResponsePostsInnerReplyId';
import {
    V1XPostsGet200ResponsePostsInnerReplyIdFromJSON,
    V1XPostsGet200ResponsePostsInnerReplyIdFromJSONTyped,
    V1XPostsGet200ResponsePostsInnerReplyIdToJSON,
    V1XPostsGet200ResponsePostsInnerReplyIdToJSONTyped,
} from './V1XPostsGet200ResponsePostsInnerReplyId';

/**
 * 
 * @export
 * @interface V1XPostsGet200ResponsePostsInnerMediasInner
 */
export interface V1XPostsGet200ResponsePostsInnerMediasInner {
    /**
     * 
     * @type {string}
     * @memberof V1XPostsGet200ResponsePostsInnerMediasInner
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof V1XPostsGet200ResponsePostsInnerMediasInner
     */
    type?: string;
    /**
     * 
     * @type {V1XPostsGet200ResponsePostsInnerReplyId}
     * @memberof V1XPostsGet200ResponsePostsInnerMediasInner
     */
    sourcePostId?: V1XPostsGet200ResponsePostsInnerReplyId;
    /**
     * 
     * @type {V1XPostsGet200ResponsePostsInnerReplyId}
     * @memberof V1XPostsGet200ResponsePostsInnerMediasInner
     */
    sourceUserId?: V1XPostsGet200ResponsePostsInnerReplyId;
    /**
     * 
     * @type {V1XPostsGet200ResponsePostsInnerMediasInnerMedia}
     * @memberof V1XPostsGet200ResponsePostsInnerMediasInner
     */
    media?: V1XPostsGet200ResponsePostsInnerMediasInnerMedia;
    /**
     * 
     * @type {V1XPostsGet200ResponsePostsInnerMediasInnerImage}
     * @memberof V1XPostsGet200ResponsePostsInnerMediasInner
     */
    image?: V1XPostsGet200ResponsePostsInnerMediasInnerImage;
    /**
     * 
     * @type {string}
     * @memberof V1XPostsGet200ResponsePostsInnerMediasInner
     */
    mediaTypeVersion?: string;
}

/**
 * Check if a given object implements the V1XPostsGet200ResponsePostsInnerMediasInner interface.
 */
export function instanceOfV1XPostsGet200ResponsePostsInnerMediasInner(value: object): value is V1XPostsGet200ResponsePostsInnerMediasInner {
    return true;
}

export function V1XPostsGet200ResponsePostsInnerMediasInnerFromJSON(json: any): V1XPostsGet200ResponsePostsInnerMediasInner {
    return V1XPostsGet200ResponsePostsInnerMediasInnerFromJSONTyped(json, false);
}

export function V1XPostsGet200ResponsePostsInnerMediasInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1XPostsGet200ResponsePostsInnerMediasInner {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'type': json['type'] == null ? undefined : json['type'],
        'sourcePostId': json['source_post_id'] == null ? undefined : V1XPostsGet200ResponsePostsInnerReplyIdFromJSON(json['source_post_id']),
        'sourceUserId': json['source_user_id'] == null ? undefined : V1XPostsGet200ResponsePostsInnerReplyIdFromJSON(json['source_user_id']),
        'media': json['media'] == null ? undefined : V1XPostsGet200ResponsePostsInnerMediasInnerMediaFromJSON(json['media']),
        'image': json['image'] == null ? undefined : V1XPostsGet200ResponsePostsInnerMediasInnerImageFromJSON(json['image']),
        'mediaTypeVersion': json['media_type_version'] == null ? undefined : json['media_type_version'],
    };
}

export function V1XPostsGet200ResponsePostsInnerMediasInnerToJSON(json: any): V1XPostsGet200ResponsePostsInnerMediasInner {
    return V1XPostsGet200ResponsePostsInnerMediasInnerToJSONTyped(json, false);
}

export function V1XPostsGet200ResponsePostsInnerMediasInnerToJSONTyped(value?: V1XPostsGet200ResponsePostsInnerMediasInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'type': value['type'],
        'source_post_id': V1XPostsGet200ResponsePostsInnerReplyIdToJSON(value['sourcePostId']),
        'source_user_id': V1XPostsGet200ResponsePostsInnerReplyIdToJSON(value['sourceUserId']),
        'media': V1XPostsGet200ResponsePostsInnerMediasInnerMediaToJSON(value['media']),
        'image': V1XPostsGet200ResponsePostsInnerMediasInnerImageToJSON(value['image']),
        'media_type_version': value['mediaTypeVersion'],
    };
}

