/* tslint:disable */
/* eslint-disable */
/**
 * api node tometome
 * API documentation.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { V1XPostsGet200ResponsePostsInner } from './V1XPostsGet200ResponsePostsInner';
import {
    V1XPostsGet200ResponsePostsInnerFromJSON,
    V1XPostsGet200ResponsePostsInnerFromJSONTyped,
    V1XPostsGet200ResponsePostsInnerToJSON,
    V1XPostsGet200ResponsePostsInnerToJSONTyped,
} from './V1XPostsGet200ResponsePostsInner';
import type { V1XUserGet200ResponseUser } from './V1XUserGet200ResponseUser';
import {
    V1XUserGet200ResponseUserFromJSON,
    V1XUserGet200ResponseUserFromJSONTyped,
    V1XUserGet200ResponseUserToJSON,
    V1XUserGet200ResponseUserToJSONTyped,
} from './V1XUserGet200ResponseUser';

/**
 * 
 * @export
 * @interface V1XPostsGet200Response
 */
export interface V1XPostsGet200Response {
    /**
     * 
     * @type {V1XUserGet200ResponseUser}
     * @memberof V1XPostsGet200Response
     */
    user?: V1XUserGet200ResponseUser;
    /**
     * List of posts.
     * @type {Array<V1XPostsGet200ResponsePostsInner>}
     * @memberof V1XPostsGet200Response
     */
    posts?: Array<V1XPostsGet200ResponsePostsInner>;
}

/**
 * Check if a given object implements the V1XPostsGet200Response interface.
 */
export function instanceOfV1XPostsGet200Response(value: object): value is V1XPostsGet200Response {
    return true;
}

export function V1XPostsGet200ResponseFromJSON(json: any): V1XPostsGet200Response {
    return V1XPostsGet200ResponseFromJSONTyped(json, false);
}

export function V1XPostsGet200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1XPostsGet200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'user': json['user'] == null ? undefined : V1XUserGet200ResponseUserFromJSON(json['user']),
        'posts': json['posts'] == null ? undefined : ((json['posts'] as Array<any>).map(V1XPostsGet200ResponsePostsInnerFromJSON)),
    };
}

export function V1XPostsGet200ResponseToJSON(json: any): V1XPostsGet200Response {
    return V1XPostsGet200ResponseToJSONTyped(json, false);
}

export function V1XPostsGet200ResponseToJSONTyped(value?: V1XPostsGet200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'user': V1XUserGet200ResponseUserToJSON(value['user']),
        'posts': value['posts'] == null ? undefined : ((value['posts'] as Array<any>).map(V1XPostsGet200ResponsePostsInnerToJSON)),
    };
}

