/* tslint:disable */
/* eslint-disable */
/**
 * api node tometome
 * API documentation.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * User information.
 * @export
 * @interface V1XUserGet200ResponseUser
 */
export interface V1XUserGet200ResponseUser {
    /**
     * 
     * @type {string}
     * @memberof V1XUserGet200ResponseUser
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof V1XUserGet200ResponseUser
     */
    username?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof V1XUserGet200ResponseUser
     */
    usernameHistory?: Array<string>;
    /**
     * 
     * @type {Date}
     * @memberof V1XUserGet200ResponseUser
     */
    postLastUpdated?: Date;
    /**
     * 
     * @type {Date}
     * @memberof V1XUserGet200ResponseUser
     */
    userLastUpdated?: Date;
}

/**
 * Check if a given object implements the V1XUserGet200ResponseUser interface.
 */
export function instanceOfV1XUserGet200ResponseUser(value: object): value is V1XUserGet200ResponseUser {
    return true;
}

export function V1XUserGet200ResponseUserFromJSON(json: any): V1XUserGet200ResponseUser {
    return V1XUserGet200ResponseUserFromJSONTyped(json, false);
}

export function V1XUserGet200ResponseUserFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1XUserGet200ResponseUser {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'username': json['username'] == null ? undefined : json['username'],
        'usernameHistory': json['username_history'] == null ? undefined : json['username_history'],
        'postLastUpdated': json['post_last_updated'] == null ? undefined : (new Date(json['post_last_updated'])),
        'userLastUpdated': json['user_last_updated'] == null ? undefined : (new Date(json['user_last_updated'])),
    };
}

export function V1XUserGet200ResponseUserToJSON(json: any): V1XUserGet200ResponseUser {
    return V1XUserGet200ResponseUserToJSONTyped(json, false);
}

export function V1XUserGet200ResponseUserToJSONTyped(value?: V1XUserGet200ResponseUser | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'username': value['username'],
        'username_history': value['usernameHistory'],
        'post_last_updated': value['postLastUpdated'] == null ? undefined : ((value['postLastUpdated']).toISOString()),
        'user_last_updated': value['userLastUpdated'] == null ? undefined : ((value['userLastUpdated']).toISOString()),
    };
}

