/* tslint:disable */
/* eslint-disable */
/**
 * api node tometome
 * API documentation.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { V1XUserGet200ResponseUser } from './V1XUserGet200ResponseUser';
import {
    V1XUserGet200ResponseUserFromJSON,
    V1XUserGet200ResponseUserFromJSONTyped,
    V1XUserGet200ResponseUserToJSON,
    V1XUserGet200ResponseUserToJSONTyped,
} from './V1XUserGet200ResponseUser';

/**
 * 
 * @export
 * @interface V1XUserGet200Response
 */
export interface V1XUserGet200Response {
    /**
     * 
     * @type {V1XUserGet200ResponseUser}
     * @memberof V1XUserGet200Response
     */
    user?: V1XUserGet200ResponseUser;
}

/**
 * Check if a given object implements the V1XUserGet200Response interface.
 */
export function instanceOfV1XUserGet200Response(value: object): value is V1XUserGet200Response {
    return true;
}

export function V1XUserGet200ResponseFromJSON(json: any): V1XUserGet200Response {
    return V1XUserGet200ResponseFromJSONTyped(json, false);
}

export function V1XUserGet200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1XUserGet200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'user': json['user'] == null ? undefined : V1XUserGet200ResponseUserFromJSON(json['user']),
    };
}

export function V1XUserGet200ResponseToJSON(json: any): V1XUserGet200Response {
    return V1XUserGet200ResponseToJSONTyped(json, false);
}

export function V1XUserGet200ResponseToJSONTyped(value?: V1XUserGet200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'user': V1XUserGet200ResponseUserToJSON(value['user']),
    };
}

