/* tslint:disable */
/* eslint-disable */
/**
 * api node tometome
 * API documentation.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { YoutubeVideo } from './YoutubeVideo';
import {
    YoutubeVideoFromJSON,
    YoutubeVideoFromJSONTyped,
    YoutubeVideoToJSON,
    YoutubeVideoToJSONTyped,
} from './YoutubeVideo';

/**
 * 
 * @export
 * @interface V1YoutubeSongsGet200Response
 */
export interface V1YoutubeSongsGet200Response {
    /**
     * 
     * @type {Array<YoutubeVideo>}
     * @memberof V1YoutubeSongsGet200Response
     */
    songs?: Array<YoutubeVideo>;
}

/**
 * Check if a given object implements the V1YoutubeSongsGet200Response interface.
 */
export function instanceOfV1YoutubeSongsGet200Response(value: object): value is V1YoutubeSongsGet200Response {
    return true;
}

export function V1YoutubeSongsGet200ResponseFromJSON(json: any): V1YoutubeSongsGet200Response {
    return V1YoutubeSongsGet200ResponseFromJSONTyped(json, false);
}

export function V1YoutubeSongsGet200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1YoutubeSongsGet200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'songs': json['songs'] == null ? undefined : ((json['songs'] as Array<any>).map(YoutubeVideoFromJSON)),
    };
}

export function V1YoutubeSongsGet200ResponseToJSON(json: any): V1YoutubeSongsGet200Response {
    return V1YoutubeSongsGet200ResponseToJSONTyped(json, false);
}

export function V1YoutubeSongsGet200ResponseToJSONTyped(value?: V1YoutubeSongsGet200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'songs': value['songs'] == null ? undefined : ((value['songs'] as Array<any>).map(YoutubeVideoToJSON)),
    };
}

