/* tslint:disable */
/* eslint-disable */
/**
 * api node tometome
 * API documentation.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface V1YoutubeSongsGet429Response
 */
export interface V1YoutubeSongsGet429Response {
    /**
     * 
     * @type {string}
     * @memberof V1YoutubeSongsGet429Response
     */
    message?: string;
}

/**
 * Check if a given object implements the V1YoutubeSongsGet429Response interface.
 */
export function instanceOfV1YoutubeSongsGet429Response(value: object): value is V1YoutubeSongsGet429Response {
    return true;
}

export function V1YoutubeSongsGet429ResponseFromJSON(json: any): V1YoutubeSongsGet429Response {
    return V1YoutubeSongsGet429ResponseFromJSONTyped(json, false);
}

export function V1YoutubeSongsGet429ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1YoutubeSongsGet429Response {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'] == null ? undefined : json['message'],
    };
}

export function V1YoutubeSongsGet429ResponseToJSON(json: any): V1YoutubeSongsGet429Response {
    return V1YoutubeSongsGet429ResponseToJSONTyped(json, false);
}

export function V1YoutubeSongsGet429ResponseToJSONTyped(value?: V1YoutubeSongsGet429Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': value['message'],
    };
}

