/* tslint:disable */
/* eslint-disable */
/**
 * api node tometome
 * API documentation.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { YoutubeRelease } from './YoutubeRelease';
import {
    YoutubeReleaseFromJSON,
    YoutubeReleaseFromJSONTyped,
    YoutubeReleaseToJSON,
    YoutubeReleaseToJSONTyped,
} from './YoutubeRelease';
import type { YoutubeVideo } from './YoutubeVideo';
import {
    YoutubeVideoFromJSON,
    YoutubeVideoFromJSONTyped,
    YoutubeVideoToJSON,
    YoutubeVideoToJSONTyped,
} from './YoutubeVideo';
import type { YoutubeReleases } from './YoutubeReleases';
import {
    YoutubeReleasesFromJSON,
    YoutubeReleasesFromJSONTyped,
    YoutubeReleasesToJSON,
    YoutubeReleasesToJSONTyped,
} from './YoutubeReleases';

/**
 * 
 * @export
 * @interface V1YoutubeReleaseGet200Response
 */
export interface V1YoutubeReleaseGet200Response {
    /**
     * 
     * @type {YoutubeReleases}
     * @memberof V1YoutubeReleaseGet200Response
     */
    release?: YoutubeReleases;
    /**
     * 
     * @type {Array<YoutubeRelease>}
     * @memberof V1YoutubeReleaseGet200Response
     */
    releaseItems?: Array<YoutubeRelease>;
    /**
     * 
     * @type {Array<YoutubeVideo>}
     * @memberof V1YoutubeReleaseGet200Response
     */
    releaseItemsVideos?: Array<YoutubeVideo>;
}

/**
 * Check if a given object implements the V1YoutubeReleaseGet200Response interface.
 */
export function instanceOfV1YoutubeReleaseGet200Response(value: object): value is V1YoutubeReleaseGet200Response {
    return true;
}

export function V1YoutubeReleaseGet200ResponseFromJSON(json: any): V1YoutubeReleaseGet200Response {
    return V1YoutubeReleaseGet200ResponseFromJSONTyped(json, false);
}

export function V1YoutubeReleaseGet200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1YoutubeReleaseGet200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'release': json['release'] == null ? undefined : YoutubeReleasesFromJSON(json['release']),
        'releaseItems': json['releaseItems'] == null ? undefined : ((json['releaseItems'] as Array<any>).map(YoutubeReleaseFromJSON)),
        'releaseItemsVideos': json['releaseItemsVideos'] == null ? undefined : ((json['releaseItemsVideos'] as Array<any>).map(YoutubeVideoFromJSON)),
    };
}

export function V1YoutubeReleaseGet200ResponseToJSON(json: any): V1YoutubeReleaseGet200Response {
    return V1YoutubeReleaseGet200ResponseToJSONTyped(json, false);
}

export function V1YoutubeReleaseGet200ResponseToJSONTyped(value?: V1YoutubeReleaseGet200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'release': YoutubeReleasesToJSON(value['release']),
        'releaseItems': value['releaseItems'] == null ? undefined : ((value['releaseItems'] as Array<any>).map(YoutubeReleaseToJSON)),
        'releaseItemsVideos': value['releaseItemsVideos'] == null ? undefined : ((value['releaseItemsVideos'] as Array<any>).map(YoutubeVideoToJSON)),
    };
}

