/* tslint:disable */
/* eslint-disable */
/**
 * api node tometome
 * API documentation.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface XPostMediasInnerMediaAspectRatio
 */
export interface XPostMediasInnerMediaAspectRatio {
    /**
     * 
     * @type {number}
     * @memberof XPostMediasInnerMediaAspectRatio
     */
    width?: number;
    /**
     * 
     * @type {number}
     * @memberof XPostMediasInnerMediaAspectRatio
     */
    height?: number;
}

/**
 * Check if a given object implements the XPostMediasInnerMediaAspectRatio interface.
 */
export function instanceOfXPostMediasInnerMediaAspectRatio(value: object): value is XPostMediasInnerMediaAspectRatio {
    return true;
}

export function XPostMediasInnerMediaAspectRatioFromJSON(json: any): XPostMediasInnerMediaAspectRatio {
    return XPostMediasInnerMediaAspectRatioFromJSONTyped(json, false);
}

export function XPostMediasInnerMediaAspectRatioFromJSONTyped(json: any, ignoreDiscriminator: boolean): XPostMediasInnerMediaAspectRatio {
    if (json == null) {
        return json;
    }
    return {
        
        'width': json['width'] == null ? undefined : json['width'],
        'height': json['height'] == null ? undefined : json['height'],
    };
}

export function XPostMediasInnerMediaAspectRatioToJSON(json: any): XPostMediasInnerMediaAspectRatio {
    return XPostMediasInnerMediaAspectRatioToJSONTyped(json, false);
}

export function XPostMediasInnerMediaAspectRatioToJSONTyped(value?: XPostMediasInnerMediaAspectRatio | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'width': value['width'],
        'height': value['height'],
    };
}

