/* tslint:disable */
/* eslint-disable */
/**
 * api node tometome
 * API documentation.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { XPostMediasInner } from './XPostMediasInner';
import {
    XPostMediasInnerFromJSON,
    XPostMediasInnerFromJSONTyped,
    XPostMediasInnerToJSON,
    XPostMediasInnerToJSONTyped,
} from './XPostMediasInner';

/**
 * 
 * @export
 * @interface XPost
 */
export interface XPost {
    /**
     * 
     * @type {string}
     * @memberof XPost
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof XPost
     */
    text?: string;
    /**
     * 
     * @type {Date}
     * @memberof XPost
     */
    publishedAt?: Date;
    /**
     * 
     * @type {string}
     * @memberof XPost
     */
    userId?: string;
    /**
     * 
     * @type {string}
     * @memberof XPost
     */
    replyId?: string;
    /**
     * 
     * @type {string}
     * @memberof XPost
     */
    repostId?: string;
    /**
     * 
     * @type {string}
     * @memberof XPost
     */
    quoteRepostId?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof XPost
     */
    urls?: Array<string>;
    /**
     * 
     * @type {Array<XPostMediasInner>}
     * @memberof XPost
     */
    medias?: Array<XPostMediasInner>;
    /**
     * 
     * @type {string}
     * @memberof XPost
     */
    mediaTypeVersion?: string;
}

/**
 * Check if a given object implements the XPost interface.
 */
export function instanceOfXPost(value: object): value is XPost {
    return true;
}

export function XPostFromJSON(json: any): XPost {
    return XPostFromJSONTyped(json, false);
}

export function XPostFromJSONTyped(json: any, ignoreDiscriminator: boolean): XPost {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'text': json['text'] == null ? undefined : json['text'],
        'publishedAt': json['published_at'] == null ? undefined : (new Date(json['published_at'])),
        'userId': json['user_id'] == null ? undefined : json['user_id'],
        'replyId': json['reply_id'] == null ? undefined : json['reply_id'],
        'repostId': json['repost_id'] == null ? undefined : json['repost_id'],
        'quoteRepostId': json['quote_repost_id'] == null ? undefined : json['quote_repost_id'],
        'urls': json['urls'] == null ? undefined : json['urls'],
        'medias': json['medias'] == null ? undefined : ((json['medias'] as Array<any>).map(XPostMediasInnerFromJSON)),
        'mediaTypeVersion': json['media_type_version'] == null ? undefined : json['media_type_version'],
    };
}

export function XPostToJSON(json: any): XPost {
    return XPostToJSONTyped(json, false);
}

export function XPostToJSONTyped(value?: XPost | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'text': value['text'],
        'published_at': value['publishedAt'] == null ? value['publishedAt'] : value['publishedAt'].toISOString(),
        'user_id': value['userId'],
        'reply_id': value['replyId'],
        'repost_id': value['repostId'],
        'quote_repost_id': value['quoteRepostId'],
        'urls': value['urls'],
        'medias': value['medias'] == null ? undefined : ((value['medias'] as Array<any>).map(XPostMediasInnerToJSON)),
        'media_type_version': value['mediaTypeVersion'],
    };
}

