/* tslint:disable */
/* eslint-disable */
/**
 * api node tometome
 * API documentation.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface XPostMediasInnerImage
 */
export interface XPostMediasInnerImage {
    /**
     * 
     * @type {string}
     * @memberof XPostMediasInnerImage
     */
    url?: string;
    /**
     * 
     * @type {number}
     * @memberof XPostMediasInnerImage
     */
    width?: number;
    /**
     * 
     * @type {number}
     * @memberof XPostMediasInnerImage
     */
    height?: number;
}

/**
 * Check if a given object implements the XPostMediasInnerImage interface.
 */
export function instanceOfXPostMediasInnerImage(value: object): value is XPostMediasInnerImage {
    return true;
}

export function XPostMediasInnerImageFromJSON(json: any): XPostMediasInnerImage {
    return XPostMediasInnerImageFromJSONTyped(json, false);
}

export function XPostMediasInnerImageFromJSONTyped(json: any, ignoreDiscriminator: boolean): XPostMediasInnerImage {
    if (json == null) {
        return json;
    }
    return {
        
        'url': json['url'] == null ? undefined : json['url'],
        'width': json['width'] == null ? undefined : json['width'],
        'height': json['height'] == null ? undefined : json['height'],
    };
}

export function XPostMediasInnerImageToJSON(json: any): XPostMediasInnerImage {
    return XPostMediasInnerImageToJSONTyped(json, false);
}

export function XPostMediasInnerImageToJSONTyped(value?: XPostMediasInnerImage | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'url': value['url'],
        'width': value['width'],
        'height': value['height'],
    };
}

