/* tslint:disable */
/* eslint-disable */
/**
 * api node tometome
 * API documentation.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { XPostMediasInner } from './XPostMediasInner';
import {
    XPostMediasInnerFromJSON,
    XPostMediasInnerFromJSONTyped,
    XPostMediasInnerToJSON,
    XPostMediasInnerToJSONTyped,
} from './XPostMediasInner';

/**
 * 
 * @export
 * @interface XRelatePost
 */
export interface XRelatePost {
    /**
     * 
     * @type {string}
     * @memberof XRelatePost
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof XRelatePost
     */
    text?: string;
    /**
     * 
     * @type {Date}
     * @memberof XRelatePost
     */
    publishedAt?: Date;
    /**
     * 
     * @type {string}
     * @memberof XRelatePost
     */
    userId?: string;
    /**
     * 
     * @type {string}
     * @memberof XRelatePost
     */
    replyId?: string;
    /**
     * 
     * @type {string}
     * @memberof XRelatePost
     */
    repostId?: string;
    /**
     * 
     * @type {string}
     * @memberof XRelatePost
     */
    quoteRepostId?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof XRelatePost
     */
    urls?: Array<string>;
    /**
     * 
     * @type {Array<XPostMediasInner>}
     * @memberof XRelatePost
     */
    medias?: Array<XPostMediasInner>;
    /**
     * 
     * @type {string}
     * @memberof XRelatePost
     */
    mediaTypeVersion?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof XRelatePost
     */
    replyByIds?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof XRelatePost
     */
    repostedByIds?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof XRelatePost
     */
    quoteRepostByIds?: Array<string>;
}

/**
 * Check if a given object implements the XRelatePost interface.
 */
export function instanceOfXRelatePost(value: object): value is XRelatePost {
    return true;
}

export function XRelatePostFromJSON(json: any): XRelatePost {
    return XRelatePostFromJSONTyped(json, false);
}

export function XRelatePostFromJSONTyped(json: any, ignoreDiscriminator: boolean): XRelatePost {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'text': json['text'] == null ? undefined : json['text'],
        'publishedAt': json['published_at'] == null ? undefined : (new Date(json['published_at'])),
        'userId': json['user_id'] == null ? undefined : json['user_id'],
        'replyId': json['reply_id'] == null ? undefined : json['reply_id'],
        'repostId': json['repost_id'] == null ? undefined : json['repost_id'],
        'quoteRepostId': json['quote_repost_id'] == null ? undefined : json['quote_repost_id'],
        'urls': json['urls'] == null ? undefined : json['urls'],
        'medias': json['medias'] == null ? undefined : ((json['medias'] as Array<any>).map(XPostMediasInnerFromJSON)),
        'mediaTypeVersion': json['media_type_version'] == null ? undefined : json['media_type_version'],
        'replyByIds': json['reply_by_ids'] == null ? undefined : json['reply_by_ids'],
        'repostedByIds': json['reposted_by_ids'] == null ? undefined : json['reposted_by_ids'],
        'quoteRepostByIds': json['quote_repost_by_ids'] == null ? undefined : json['quote_repost_by_ids'],
    };
}

export function XRelatePostToJSON(json: any): XRelatePost {
    return XRelatePostToJSONTyped(json, false);
}

export function XRelatePostToJSONTyped(value?: XRelatePost | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'text': value['text'],
        'published_at': value['publishedAt'] == null ? value['publishedAt'] : value['publishedAt'].toISOString(),
        'user_id': value['userId'],
        'reply_id': value['replyId'],
        'repost_id': value['repostId'],
        'quote_repost_id': value['quoteRepostId'],
        'urls': value['urls'],
        'medias': value['medias'] == null ? undefined : ((value['medias'] as Array<any>).map(XPostMediasInnerToJSON)),
        'media_type_version': value['mediaTypeVersion'],
        'reply_by_ids': value['replyByIds'],
        'reposted_by_ids': value['repostedByIds'],
        'quote_repost_by_ids': value['quoteRepostByIds'],
    };
}

