/* tslint:disable */
/* eslint-disable */
/**
 * api node tometome
 * API documentation.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface XText
 */
export interface XText {
    /**
     * 
     * @type {number}
     * @memberof XText
     */
    weightedLength?: number;
    /**
     * 
     * @type {boolean}
     * @memberof XText
     */
    valid?: boolean;
    /**
     * 
     * @type {number}
     * @memberof XText
     */
    permillage?: number;
    /**
     * 
     * @type {number}
     * @memberof XText
     */
    validRangeStart?: number;
    /**
     * 
     * @type {number}
     * @memberof XText
     */
    validRangeEnd?: number;
    /**
     * 
     * @type {number}
     * @memberof XText
     */
    displayRangeStart?: number;
    /**
     * 
     * @type {number}
     * @memberof XText
     */
    displayRangeEnd?: number;
}

/**
 * Check if a given object implements the XText interface.
 */
export function instanceOfXText(value: object): value is XText {
    return true;
}

export function XTextFromJSON(json: any): XText {
    return XTextFromJSONTyped(json, false);
}

export function XTextFromJSONTyped(json: any, ignoreDiscriminator: boolean): XText {
    if (json == null) {
        return json;
    }
    return {
        
        'weightedLength': json['weightedLength'] == null ? undefined : json['weightedLength'],
        'valid': json['valid'] == null ? undefined : json['valid'],
        'permillage': json['permillage'] == null ? undefined : json['permillage'],
        'validRangeStart': json['validRangeStart'] == null ? undefined : json['validRangeStart'],
        'validRangeEnd': json['validRangeEnd'] == null ? undefined : json['validRangeEnd'],
        'displayRangeStart': json['displayRangeStart'] == null ? undefined : json['displayRangeStart'],
        'displayRangeEnd': json['displayRangeEnd'] == null ? undefined : json['displayRangeEnd'],
    };
}

export function XTextToJSON(json: any): XText {
    return XTextToJSONTyped(json, false);
}

export function XTextToJSONTyped(value?: XText | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'weightedLength': value['weightedLength'],
        'valid': value['valid'],
        'permillage': value['permillage'],
        'validRangeStart': value['validRangeStart'],
        'validRangeEnd': value['validRangeEnd'],
        'displayRangeStart': value['displayRangeStart'],
        'displayRangeEnd': value['displayRangeEnd'],
    };
}

