/* tslint:disable */
/* eslint-disable */
/**
 * api node tometome
 * API documentation.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface XTextPostRequest
 */
export interface XTextPostRequest {
    /**
     * 
     * @type {string}
     * @memberof XTextPostRequest
     */
    text: string;
}

/**
 * Check if a given object implements the XTextPostRequest interface.
 */
export function instanceOfXTextPostRequest(value: object): value is XTextPostRequest {
    if (!('text' in value) || value['text'] === undefined) return false;
    return true;
}

export function XTextPostRequestFromJSON(json: any): XTextPostRequest {
    return XTextPostRequestFromJSONTyped(json, false);
}

export function XTextPostRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): XTextPostRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'text': json['text'],
    };
}

export function XTextPostRequestToJSON(json: any): XTextPostRequest {
    return XTextPostRequestToJSONTyped(json, false);
}

export function XTextPostRequestToJSONTyped(value?: XTextPostRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'text': value['text'],
    };
}

