/* tslint:disable */
/* eslint-disable */
/**
 * api node tometome
 * API documentation.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface YoutubeVideo
 */
export interface YoutubeVideo {
    /**
     * 
     * @type {string}
     * @memberof YoutubeVideo
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof YoutubeVideo
     */
    ownerChannelId?: string;
    /**
     * 
     * @type {string}
     * @memberof YoutubeVideo
     */
    channelId?: string;
    /**
     * 
     * @type {Date}
     * @memberof YoutubeVideo
     */
    publishedAt?: Date;
    /**
     * 
     * @type {string}
     * @memberof YoutubeVideo
     */
    privacyStatus?: string;
    /**
     * 
     * @type {boolean}
     * @memberof YoutubeVideo
     */
    _short?: boolean;
    /**
     * 
     * @type {string}
     * @memberof YoutubeVideo
     */
    musicType?: string;
    /**
     * 
     * @type {string}
     * @memberof YoutubeVideo
     */
    thumbnailUrl?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof YoutubeVideo
     */
    artistId?: Array<string>;
    /**
     * 
     * @type {number}
     * @memberof YoutubeVideo
     */
    duration?: number;
}

/**
 * Check if a given object implements the YoutubeVideo interface.
 */
export function instanceOfYoutubeVideo(value: object): value is YoutubeVideo {
    return true;
}

export function YoutubeVideoFromJSON(json: any): YoutubeVideo {
    return YoutubeVideoFromJSONTyped(json, false);
}

export function YoutubeVideoFromJSONTyped(json: any, ignoreDiscriminator: boolean): YoutubeVideo {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'ownerChannelId': json['owner_channel_id'] == null ? undefined : json['owner_channel_id'],
        'channelId': json['channel_id'] == null ? undefined : json['channel_id'],
        'publishedAt': json['published_at'] == null ? undefined : (new Date(json['published_at'])),
        'privacyStatus': json['privacy_status'] == null ? undefined : json['privacy_status'],
        '_short': json['short'] == null ? undefined : json['short'],
        'musicType': json['music_type'] == null ? undefined : json['music_type'],
        'thumbnailUrl': json['thumbnail_url'] == null ? undefined : json['thumbnail_url'],
        'artistId': json['artist_id'] == null ? undefined : json['artist_id'],
        'duration': json['duration'] == null ? undefined : json['duration'],
    };
}

export function YoutubeVideoToJSON(json: any): YoutubeVideo {
    return YoutubeVideoToJSONTyped(json, false);
}

export function YoutubeVideoToJSONTyped(value?: YoutubeVideo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'owner_channel_id': value['ownerChannelId'],
        'channel_id': value['channelId'],
        'published_at': value['publishedAt'] == null ? value['publishedAt'] : value['publishedAt'].toISOString(),
        'privacy_status': value['privacyStatus'],
        'short': value['_short'],
        'music_type': value['musicType'],
        'thumbnail_url': value['thumbnailUrl'],
        'artist_id': value['artistId'],
        'duration': value['duration'],
    };
}

